/* ============================================================
   Profil Aset NTT — Data Aset
   Peta Pemanfaat Aset Pihak Ketiga
   Provinsi Nusa Tenggara Timur
   ============================================================ */

window.SIMANTAB_ASSETS = [
  {
    id: 1,
    pemanfaat: "PT Flobamor – Hotel Sasando",
    lokasi: "Jl. R.A. Kartini, Kelurahan Kelapa Lima",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.150040, lng: 123.615995,
    nama: "PT Flobamor – Hotel Sasando",
    alamat: "Jl. R.A. Kartini, Kelapa Lima, Kota Kupang, NTT",
    kondisi: "Hotel/bangunan eksisting",
    luas: "±18.214 m²",
    klasifikasi: "Aset tanah dan bangunan / fasilitas perhotelan",
    statusHak: "Aset milik Pemerintah Provinsi NTT, dimanfaatkan melalui KSP PT Flobamor",
    tersedia: "Tidak tersedia untuk pemanfaatan bebas — terikat KSP",
    sertifikat: "SU No. 15/1983, HPL 1/1984",
    keterangan: "Kerja Sama Pemanfaatan (KSP) dengan PT Flobamor, kontrak 30 tahun sejak 26 Agustus 2019. Nilai KSP: 2019 Rp315.000.000; 2020–2023 Rp750.550.000/tahun",
    harga: "Rp 3.642.800.000",
    opd: "",
    image: "asset/sasando.jpg"
  },
  {
    id: 2,
    pemanfaat: "PT Sarana Investama Manggabar",
    lokasi: "Jl. Pantai Pede, Gorontalo, Kecamatan Komodo",
    kabupaten: "Manggarai Barat",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -8.506741, lng: 119.878630,
    nama: "PT. Sarana Investama Manggabar",
    alamat: "Jl. Pantai Pede, Gorontalo, Kecamatan Komodo, Kabupaten Manggarai Barat, Nusa Tenggara Timur",
    kondisi: "Aset/tanah kawasan Pantai Pede untuk pembangunan hotel dan fasilitas pendukung",
    luas: "±31.670 m²",
    klasifikasi: "Tanah dan aset kerja sama BGS",
    statusHak: "Kerja sama BGS telah diputus oleh Pemprov NTT; terdapat proses/perkara hukum",
    tersedia: "Tidak tersedia bebas — status pemanfaatan masih terkait penyelesaian hukum",
    sertifikat: "HPL No. 2 Tahun 2016; terdapat HGB No. 00034/Desa Gorontalo",
    keterangan: "Kontrak HK.530 Tahun 2014 tanggal 23 Mei 2014, pola Bangun Guna Serah (BGS), masa kontrak 25 tahun. Kemudian kerja sama dengan PT SIM diputus dan aset direncanakan/dialihkan untuk kerja sama dengan PT Flobamor. Kontribusi seharusnya sekitar Rp1.547.958.670,18 per tahun.",
    harga: "Rp 1.266.800.000",
    opd: "",
    image: ""
  },
  {
    id: 3,
    pemanfaat: "PT Komodo Kawisata Pratama",
    lokasi: "Pulau Purung, Warloka, Kecamatan Komodo",
    kabupaten: "Manggarai Barat",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -8.582391, lng: 119.799959,
    nama: "PT. Komodo Kawisata Pratama",
    alamat: "Pulau Purung, Warloka, Kecamatan Komodo, Kabupaten Manggarai Barat, Nusa Tenggara Timur",
    kondisi: "Tanah/pulau; belum terdapat pembangunan resort yang terealisasi",
    luas: "±13,07 ha (±130.700 m²)",
    klasifikasi: "Tanah/aset pulau kecil – kerja sama pemanfaatan",
    statusHak: "Kerja Sama Pemanfaatan (KSP) selama 30 tahun dengan PT Komodo Kawisata Pratama",
    tersedia: "Tidak tersedia – sedang dalam masa kerja sama",
    sertifikat: "Perlu verifikasi pada dokumen sertifikat/aset BPAD",
    keterangan: "Direncanakan untuk pembangunan Warloka/Purung Marina Resort. Peletakan batu pertama Oktober 2021, namun per Maret 2025 belum ada pembangunan fisik. Pemprov menyatakan kerja sama dapat diputus apabila sampai Agustus 2026 belum ada pembangunan.",
    harga: "Rp 332.762.200",
    opd: "",
    image: ""
  },
  {
    id: 4,
    pemanfaat: "PT Asiabeef Biofarm Indonesia",
    lokasi: "Lai Lanjang, Kecamatan Rindi",
    kabupaten: "Sumba Timur",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.051043, lng: 120.637164,
    nama: "PT. Asiabeef Biofarm Indonesia",
    alamat: "Lai Lanjang, Kecamatan Rindi, Kabupaten Sumba Timur, Nusa Tenggara Timur",
    kondisi: "Lahan peternakan; terdapat rencana/pengembangan instalasi peternakan",
    luas: "Belum dapat dipastikan dari dokumen yang tersedia",
    klasifikasi: "Tanah/aset Pemprov NTT – pemanfaatan untuk peternakan",
    statusHak: "Kerja sama pemanfaatan dengan PT Asiabeef Biofarm Indonesia",
    tersedia: "Tidak tersedia – sedang dimanfaatkan dalam kerja sama",
    sertifikat: "Belum ditemukan nomor sertifikat aset Pemprov NTT yang dapat diverifikasi",
    keterangan: "Perjanjian kerja sama pemanfaatan lahan dan pembangunan gedung instalasi peternakan ditandatangani 10 Maret 2023 antara Pemprov NTT dan PT Asiabeef Biofarm Indonesia.",
    harga: "Belum ditemukan nilai aset tanah yang dapat diverifikasi",
    opd: "",
    image: "asset/PT Asiabeef Biofarm Indonesia.webp"
  },
  {
    id: 5,
    pemanfaat: "Pariwisata Estate Fatumnasi",
    lokasi: "Desa Fatumnasi, Kecamatan Fatumnasi",
    kabupaten: "Timor Tengah Selatan",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -9.7500, lng: 124.3000,
    nama: "Pariwisata Estate Fatumnasi",
    alamat: "Desa Fatumnasi, Kecamatan Fatumnasi, Kabupaten Timor Tengah Selatan, NTT",
    kondisi: "Fasilitas pariwisata tersedia: cottage, lopo, restoran, toilet dan fasilitas pendukung",
    luas: "Belum ditemukan data luas kawasan/aset yang dapat diverifikasi",
    klasifikasi: "Aset/fasilitas pariwisata",
    statusHak: "Tanah milik Pemkab TTS; bangunan/amenitas milik Pemprov NTT",
    tersedia: "Tidak – merupakan fasilitas pariwisata yang sedang dikelola",
    sertifikat: "Bukan aset tanah Pemprov NTT; tanah merupakan milik Pemkab TTS",
    keterangan: "Pengelolaan dilakukan bersama Pemprov NTT dan Pemkab TTS melalui MOU. Secara operasional pernah dikelola Sahid T-More Hotel sejak 2022; kerja sama berakhir 2023 dan selanjutnya pengelolaan kembali oleh Dinas Parekraf NTT dengan dukungan Pokdarwis.",
    harga: "Belum ditemukan nilai aset yang dapat diverifikasi",
    opd: "",
    image: "asset/Pariwisata Estate Fatumnasi.webp"
  },
  {
    id: 6,
    pemanfaat: "PT Nusa Bahana Niaga / Lippo Group",
    lokasi: "Lippo Plaza Kupang, Jl. Veteran, Kelurahan Fatululi, Kecamatan Oebobo",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.158877, lng: 123.611219,
    nama: "PT. Nusa Bahana Niaga / Lippo Group",
    alamat: "Jl. Veteran, Kelurahan Fatululi, Kecamatan Oebobo, Kota Kupang, NTT",
    kondisi: "Terbangun dan beroperasi — kompleks Lippo Plaza Kupang & Siloam Hospitals Kupang",
    luas: "±60.060 m²",
    klasifikasi: "Tanah milik Pemprov NTT – Bangun Guna Serah (BGS)",
    statusHak: "BGS, berdasarkan kontrak HK 34 Tahun 2016",
    tersedia: "Tidak tersedia – sedang dalam masa kerja sama",
    sertifikat: "Hak Pakai No. 11 Tahun 2000; SHGB No. 247/Fatululi untuk PT Nusa Bahana Niaga",
    keterangan: "Kerja sama Pemprov NTT dengan PT Nusa Bahana Niaga untuk pengembangan kawasan Siloam Hospitals Kupang dan Lippo Plaza Kupang. Kontrak awal kemudian diadendum pada 5 Desember 2016. Jangka waktu 25 tahun.",
    harga: "Rp 1.323.000.000/tahun",
    opd: "",
    image: "asset/PT Nusa Bahana Niaga : Lippo Group.jpeg"
  },
  {
    id: 7,
    pemanfaat: "PT Suba Suka GO – BGS",
    lokasi: "Jl. Cak Doko, Kelurahan Oetete, Kecamatan Oebobo",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.164305, lng: 123.590267,
    nama: "PT. Suba Suka GO (Bidang I)",
    alamat: "Jl. Cak Doko, Kelurahan Oetete, Kecamatan Oebobo, Kota Kupang, NTT",
    kondisi: "Tanah dimanfaatkan untuk pembangunan dan pengelolaan Departement Store, Book Store, Centra Kuliner dan fasilitas pendukung",
    luas: "±1.710 m² (Sertifikat No. 7/1999)",
    klasifikasi: "Tanah/aset Pemprov NTT – Bangun Guna Serah (BGS)",
    statusHak: "BGS, berdasarkan Kontrak No. HK.18 Tahun 2016",
    tersedia: "Tidak tersedia – sedang dalam masa BGS",
    sertifikat: "Hak Pakai No. 7 Tahun 1999",
    keterangan: "BGS berlaku 30 tahun dan tidak diperpanjang. Addendum PKS ditandatangani.",
    harga: "Rp 256.500.000",
    opd: "",
    image: "asset/PT Suba Suka GO – BGS.webp"
  },
  {
    id: 8,
    pemanfaat: "PT Suba Suka GO – BGS (B)",
    lokasi: "Jl. Cak Doko, Kelurahan Oetete, Kecamatan Oebobo",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.163700, lng: 123.591000,
    nama: "PT. Suba Suka GO (Bidang II)",
    alamat: "Jl. Cak Doko, Kelurahan Oetete, Kecamatan Oebobo, Kota Kupang, NTT",
    kondisi: "Tanah dimanfaatkan untuk pembangunan dan pengelolaan Departement Store, Book Store, Centra Kuliner dan fasilitas pendukung",
    luas: "±6.595 m² (Sertifikat No. 8/1999)",
    klasifikasi: "Tanah/aset Pemprov NTT – Bangun Guna Serah (BGS)",
    statusHak: "BGS, berdasarkan Kontrak No. HK.18 Tahun 2016",
    tersedia: "Tidak tersedia – sedang dalam masa BGS",
    sertifikat: "Hak Pakai No. 8 Tahun 1999",
    keterangan: "BGS berlaku 30 tahun dan tidak diperpanjang. Total nilai tanah kedua bidang Rp1.245.750.000.",
    harga: "Rp 989.250.000",
    opd: "",
    image: "asset/PT Suba Suka GO – BGS.webp"
  },
  {
    id: 9,
    pemanfaat: "PT Inspirasi Investama Raya",
    lokasi: "Jl. Timor Raya, Kelurahan Pasir Panjang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Kerjasama Pemanfaatan dengan Pihak Ketiga",
    statusClass: "kerjasama",
    lat: -10.1620, lng: 123.5920,
    nama: "PT. Inspirasi Investama Raya",
    alamat: "Jl. Timor Raya, Kelurahan Pasir Panjang, Kota Kupang, NTT",
    kondisi: "Terbangun/dimanfaatkan untuk area bisnis, hotel, kuliner dan fasilitas pendukung",
    luas: "±12.040 m²",
    klasifikasi: "Tanah milik Pemprov NTT – BGS",
    statusHak: "Bangun Guna Serah (BGS)",
    tersedia: "Tidak – sedang dalam masa kerja sama",
    sertifikat: "HP No. 11/2000",
    keterangan: "Kontrak No. HK.01 Tahun 2016 dan No. 20/IIR/PKS/I/2016, tanggal 20 Januari 2016, dengan masa kontrak 30 tahun. Kontribusi Rp365.051.627/tahun.",
    harga: "Rp 481.600.000",
    opd: "",
    image: ""
  },
  {
    id: 10,
    pemanfaat: "Tanah Kosong — Asrama Depok",
    lokasi: "Jl. Yahya Nuih No. 33, Kemiri Muka, Depok",
    kabupaten: "Jawa Barat",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -6.371265, lng: 106.838398,
    nama: "Tanah Bangunan Asrama Depok",
    alamat: "Jl. Yahya Nuih No. 33, Kemiri Muka, Depok, Jawa Barat",
    kondisi: "Tanah kosong, belum dimanfaatkan",
    luas: "705 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Hak Pakai — dikelola Badan Penghubung Provinsi NTT di Jakarta",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP No. 00003/2003",
    keterangan: "Dikelola oleh Badan Penghubung Provinsi NTT di Jakarta. Tanah kosong, belum ada pemanfaatan.",
    harga: "Belum dinilai",
    opd: "Badan Penghubung Provinsi NTT",
    image: ""
  },
  {
    id: 11,
    pemanfaat: "Tanah Kosong — Asrama Bandung",
    lokasi: "Jl. Ahmad Yani No. 36, Kel. Antapani, Kota Bandung",
    kabupaten: "Jawa Barat",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -6.904859, lng: 107.649336,
    nama: "Tanah Bangunan Asrama Bandung",
    alamat: "Jl. Ahmad Yani No. 36, Kel. Antapani, Kota Bandung, Jawa Barat",
    kondisi: "Tanah kosong, belum dimanfaatkan",
    luas: "3.975 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Hak Pakai — dikelola Badan Penghubung Provinsi NTT di Jakarta",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP No. 2/1993",
    keterangan: "Dikelola oleh Badan Penghubung Provinsi NTT di Jakarta. Tanah kosong, belum ada pemanfaatan.",
    harga: "Belum dinilai",
    opd: "Badan Penghubung Provinsi NTT",
    image: ""
  },
  {
    id: 12,
    pemanfaat: "Tanah Kosong — Asrama Yogyakarta",
    lokasi: "Kel. Tegal Panggung, Kec. Danurejan, Kota Yogyakarta",
    kabupaten: "DI Yogyakarta",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -7.791930, lng: 110.371096,
    nama: "Tanah Bangunan Asrama Yogyakarta",
    alamat: "Kel. Tegal Panggung, Kec. Danurejan, Kota Yogyakarta, DI Yogyakarta",
    kondisi: "Tanah kosong, belum dimanfaatkan",
    luas: "504 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Hak Pakai — dikelola Badan Penghubung Provinsi NTT di Jakarta",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP No. 7/Tgp/1992",
    keterangan: "Dikelola oleh Badan Penghubung Provinsi NTT di Jakarta. Tanah kosong, belum ada pemanfaatan.",
    harga: "Belum dinilai",
    opd: "Badan Penghubung Provinsi NTT",
    image: ""
  },
  {
    id: 13,
    pemanfaat: "Tanah Kosong — Sisa Shopping Center",
    lokasi: "Jl. Veteran, Fatululi, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.159, lng: 123.610,
    nama: "Sisa Tanah Kosong Shopping Center",
    alamat: "Jl. Veteran, Fatululi, Kota Kupang, NTT",
    kondisi: "Sisa tanah kosong yang belum dimanfaatkan",
    luas: "78.116 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Dikelola Badan Pendapatan dan Aset Daerah",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Sisa tanah kosong Shopping Center yang belum dimanfaatkan. Dikelola BPAD.",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 14,
    pemanfaat: "Tanah Kosong — Oesapa Barat",
    lokasi: "Jl. Timor Raya, Oesapa Barat, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.113086, lng: 123.736158,
    nama: "Tanah Kosong yang Sudah Diperuntukkan",
    alamat: "Jl. Timor Raya, Oesapa Barat, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "1.400 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Dikelola Dinas Pendidikan dan Kebudayaan",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Tanah kosong yang sudah diperuntukkan. Dikelola Dinas P&K.",
    harga: "Belum dinilai",
    opd: "Dinas Pendidikan dan Kebudayaan",
    image: ""
  },
  {
    id: 16,
    pemanfaat: "Tanah & Bangunan — Kantor Pos Oepura",
    lokasi: "Jl. Soeharto, Kel. Oepura, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.184759, lng: 123.604021,
    nama: "Tanah & Bangunan Kantor Pos dan Giro Oepura",
    alamat: "Jl. Soeharto, Kel. Oepura, Kota Kupang, NTT",
    kondisi: "Tanah/bangunan",
    luas: "1.989 m²",
    klasifikasi: "Tanah dan bangunan aset Pemprov NTT",
    statusHak: "Dikelola Sekretariat Daerah Provinsi NTT",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Dikelola Setda Provinsi NTT.",
    harga: "Belum dinilai",
    opd: "Sekretariat Daerah Provinsi NTT",
    image: "asset/Kantor Pos Oepura.png"
  },
  {
    id: 17,
    pemanfaat: "Tanah & Lapangan — Helipad El Tari",
    lokasi: "Jl. El Tari, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.177780, lng: 123.662632,
    nama: "Tanah & Bangunan Lapangan Helikopter",
    alamat: "Jl. El Tari, Kota Kupang, NTT",
    kondisi: "Tanah/lapangan",
    luas: "12.255 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 506/1988 — dikelola Sekretariat Daerah Provinsi NTT",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 506/1988",
    keterangan: "Tanah dan bangunan lapangan helikopter. Dikelola Setda Provinsi NTT.",
    harga: "Belum dinilai",
    opd: "Sekretariat Daerah Provinsi NTT",
    image: ""
  },
  {
    id: 18,
    pemanfaat: "Tanah Lapangan Bola Voli",
    lokasi: "Kel. Kelapa Lima, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.1488, lng: 123.6165,
    nama: "Tanah Lapangan Bola Voli",
    alamat: "Kel. Kelapa Lima, Kota Kupang, NTT",
    kondisi: "Tanah/lapangan",
    luas: "3.220 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 534/1988 — dikelola Sekretariat Daerah Provinsi NTT",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 534/1988",
    keterangan: "Tanah lapangan bola voli. Dikelola Setda Provinsi NTT.",
    harga: "Belum dinilai",
    opd: "Sekretariat Daerah Provinsi NTT",
    image: ""
  },
  {
    id: 19,
    pemanfaat: "Tanah Kosong — Samping RS AL",
    lokasi: "Jl. Yos Sudarso–Namosain, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.190, lng: 123.545,
    nama: "Tanah Sisa Penyerahan ke RS Angkatan Laut",
    alamat: "Jl. Yos Sudarso–Namosain, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "3.628 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Dikelola Sekretariat Daerah Provinsi NTT",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Tanah sisa penyerahan ke RS Angkatan Laut. Dikelola Setda Provinsi NTT.",
    harga: "Belum dinilai",
    opd: "Sekretariat Daerah Provinsi NTT",
    image: ""
  },
  {
    id: 20,
    pemanfaat: "Tanah & Bangunan — DWP Prov NTT",
    lokasi: "Jl. Cak Doko, Kel. Oebobo, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.165936, lng: 123.595200,
    nama: "Tanah Bangunan DWP Prov. NTT",
    alamat: "Jl. Cak Doko, Kel. Oebobo, Kota Kupang, NTT",
    kondisi: "Tanah/bangunan",
    luas: "2.439 m²",
    klasifikasi: "Tanah dan bangunan aset Pemprov NTT",
    statusHak: "HP. 470/1981 — dikelola Sekretariat Daerah Provinsi NTT",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 470/1981",
    keterangan: "Tanah bangunan Dharma Wanita Persatuan Provinsi NTT. Dikelola Setda.",
    harga: "Belum dinilai",
    opd: "Sekretariat Daerah Provinsi NTT",
    image: ""
  },
  {
    id: 21,
    pemanfaat: "Tanah Kosong — Namosain",
    lokasi: "Kel. Namosain, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.195, lng: 123.540,
    nama: "Tanah Sisa Namosain (HPL 3/1986)",
    alamat: "Kel. Namosain, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Sisa setelah sebagian digunakan PT Semen Kupang",
    luas: "3.079.830 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HPL. 3/1986 — dikelola BPAD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HPL. 3/1986",
    keterangan: "Luasan tersisa setelah sebagian digunakan PT Semen Kupang dan dihibahkan ke Pemkot Kupang.",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 23,
    pemanfaat: "Tanah & Bangunan — Bank Bukopin",
    lokasi: "Jl. Tompelo No. 4, Kel. Fontein, Kec. Oebobo",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.164028, lng: 123.583859,
    nama: "Tanah Bangunan Bank Bukopin (Eks Ade Irma)",
    alamat: "Jl. Tompelo No. 4, Kel. Fontein, Kec. Oebobo, Kota Kupang, NTT",
    kondisi: "Tanah/bangunan",
    luas: "1.220 m²",
    klasifikasi: "Tanah dan bangunan aset Pemprov NTT",
    statusHak: "Dikelola BPAD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Tanah bangunan gedung Bank Bukopin (eks Gedung Ade Irma).",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 24,
    pemanfaat: "Tanah Kosong — Oesapa Dekat Jembatan",
    lokasi: "Jl. Timor Raya, Oesapa Barat, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.149671, lng: 123.653941,
    nama: "Tanah Kosong Oesapa Dekat Jembatan",
    alamat: "Jl. Timor Raya, Oesapa Barat, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "1.400 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "GS. 145/1979 — dikelola Dinas P&K",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "GS. 145/1979",
    keterangan: "Tanah kosong Kel. Oesapa dekat jembatan. Dikelola Dinas P&K.",
    harga: "Belum dinilai",
    opd: "Dinas Pendidikan dan Kebudayaan",
    image: ""
  },
  {
    id: 25,
    pemanfaat: "Tanah Kosong — Perintis Kemerdekaan",
    lokasi: "Jl. Perintis Kemerdekaan III, Kel. Kelapa Lima",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.152461, lng: 123.621668,
    nama: "Tanah Kosong Perintis Kemerdekaan III",
    alamat: "Jl. Perintis Kemerdekaan III, Kel. Kelapa Lima, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "2.154 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP No. 52 — dikelola DLHK",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP No. 52",
    keterangan: "Tanah kosong. Dikelola Dinas Lingkungan Hidup dan Kehutanan.",
    harga: "Belum dinilai",
    opd: "Dinas Lingkungan Hidup dan Kehutanan",
    image: ""
  },
  {
    id: 26,
    pemanfaat: "Tanah Perkemahan Pramuka",
    lokasi: "Perkemahan Pramuka, Kec. Kupang Barat/Oenesu",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.267272, lng: 123.567914,
    nama: "Tanah Perkemahan Pramuka",
    alamat: "Perkemahan Pramuka, Kec. Kupang Barat/Oenesu, Kab. Kupang, NTT",
    kondisi: "Perkemahan Pramuka",
    luas: "8.373 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "GS. 296/1995 — dikelola Dinas P&K",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "GS. 296/1995",
    keterangan: "Tanah Perkemahan Pramuka Kec. Kupang Barat/Oenesu. Dikelola Dinas P&K.",
    harga: "Belum dinilai",
    opd: "Dinas Pendidikan dan Kebudayaan",
    image: ""
  },
  {
    id: 27,
    pemanfaat: "Tanah Kebun Percobaan",
    lokasi: "Jl. Timor Raya, Oesao, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.086357, lng: 123.862712,
    nama: "Tanah Kebun Percobaan",
    alamat: "Jl. Timor Raya, Oesao, Kab. Kupang, NTT",
    kondisi: "Tanah kebun percobaan",
    luas: "10.275 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 629",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 629",
    keterangan: "Tanah kebun percobaan di Oesao.",
    harga: "Belum dinilai",
    opd: "—",
    image: ""
  },
  {
    id: 28,
    pemanfaat: "Tanah/Gudang Buku SD Namosain",
    lokasi: "Jl. M. Praja, Kel. Namosain, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.175714, lng: 123.553252,
    nama: "Tanah/Gudang Buku SD",
    alamat: "Jl. M. Praja, Kel. Namosain, Kota Kupang, NTT",
    kondisi: "Gudang Buku SD",
    luas: "1.200 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "GS. 508/1975 — dikelola Dinas P&K",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "GS. 508/1975",
    keterangan: "Tanah/Gudang Buku SD Kel. Namosain. Dikelola Dinas P&K.",
    harga: "Belum dinilai",
    opd: "Dinas Pendidikan dan Kebudayaan",
    image: ""
  },
  {
    id: 29,
    pemanfaat: "Tanah Manulai II (HP 07)",
    lokasi: "Kel. Manulai II, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.205736, lng: 123.560508,
    nama: "Tanah Sisa Belum Bersertifikat",
    alamat: "Kel. Manulai II, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Tanah sisa yang belum bersertifikat",
    luas: "286.976 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 07/2016 — dikelola Dinas PMD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 07/2016",
    keterangan: "Tanah sisa yang belum bersertifikat. Dikelola Dinas Pemberdayaan Masyarakat dan Desa.",
    harga: "Belum dinilai",
    opd: "Dinas Pemberdayaan Masyarakat dan Desa",
    image: ""
  },
  {
    id: 30,
    pemanfaat: "Tanah Manulai II (HP 14)",
    lokasi: "Kel. Manulai II, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.2052, lng: 123.5615,
    nama: "Tanah Manulai II HP 14/2021",
    alamat: "Kel. Manulai II, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "12.510 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 14/2021 — dikelola Dinas PMD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 14/2021",
    keterangan: "Dikelola Dinas Pemberdayaan Masyarakat dan Desa.",
    harga: "Belum dinilai",
    opd: "Dinas Pemberdayaan Masyarakat dan Desa",
    image: ""
  },
  {
    id: 31,
    pemanfaat: "Tanah Manulai II (HP 15)",
    lokasi: "Kel. Manulai II, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.2048, lng: 123.5628,
    nama: "Tanah Manulai II HP 15/2021",
    alamat: "Kel. Manulai II, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "20.900 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 15/2021 — dikelola Dinas PMD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 15/2021",
    keterangan: "Dikelola Dinas Pemberdayaan Masyarakat dan Desa.",
    harga: "Belum dinilai",
    opd: "Dinas Pemberdayaan Masyarakat dan Desa",
    image: ""
  },
  {
    id: 32,
    pemanfaat: "Tanah Manulai II (HP 17)",
    lokasi: "Kel. Manulai II, Kec. Alak, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.2045, lng: 123.5640,
    nama: "Tanah Manulai II HP 17/2021",
    alamat: "Kel. Manulai II, Kec. Alak, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "18.000 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 17/2021 — dikelola Dinas PMD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 17/2021",
    keterangan: "Dikelola Dinas Pemberdayaan Masyarakat dan Desa.",
    harga: "Belum dinilai",
    opd: "Dinas Pemberdayaan Masyarakat dan Desa",
    image: ""
  },
  {
    id: 33,
    pemanfaat: "Tanah Lasiana",
    lokasi: "Jl. Timor Raya, Kel. Lasiana, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.142763, lng: 123.669765,
    nama: "Tanah Lasiana HP 06/2000",
    alamat: "Jl. Timor Raya, Kel. Lasiana, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "33.245 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 06/2000 — dikelola Dinas Perhubungan",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 06/2000",
    keterangan: "Dikelola Dinas Perhubungan.",
    harga: "Belum dinilai",
    opd: "Dinas Perhubungan",
    image: ""
  },
  {
    id: 34,
    pemanfaat: "Tanah Pos Penampungan Nener",
    lokasi: "Desa Humusu B, Kec. Insana, Kab. TTU",
    kabupaten: "Timor Tengah Utara",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -9.227555, lng: 124.570354,
    nama: "Tanah untuk Pos Penampungan Nener",
    alamat: "Desa Humusu B, Kec. Insana, Kab. Timor Tengah Utara, NTT",
    kondisi: "Tanah",
    luas: "21.275 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 001 — dikelola Dinas Kelautan dan Perikanan",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 001",
    keterangan: "Tanah untuk Pos Penampungan Nener. Dikelola Dinas Kelautan dan Perikanan.",
    harga: "Belum dinilai",
    opd: "Dinas Kelautan dan Perikanan",
    image: ""
  },
  {
    id: 35,
    pemanfaat: "Tanah Bangunan Kantor Dinas",
    lokasi: "Maubeli, Kota Kefamenanu, Kab. TTU",
    kabupaten: "Timor Tengah Utara",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -9.491631, lng: 124.493977,
    nama: "Tanah Bangunan Kantor Dinas Pertanian",
    alamat: "Maubeli, Kota Kefamenanu, Kab. Timor Tengah Utara, NTT",
    kondisi: "Tanah/bangunan",
    luas: "746 m²",
    klasifikasi: "Tanah dan bangunan aset Pemprov NTT",
    statusHak: "HP. 07/2013 — dikelola Dinas Pertanian dan Ketahanan Pangan",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 07/2013",
    keterangan: "Tanah Bangunan Kantor Dinas. Dikelola Dinas Pertanian dan Ketahanan Pangan.",
    harga: "Belum dinilai",
    opd: "Dinas Pertanian dan Ketahanan Pangan",
    image: ""
  },
  {
    id: 36,
    pemanfaat: "Tanah Peternakan Kabaru",
    lokasi: "Desa Kabaru, Kec. Rindi, Kab. Sumba Timur",
    kabupaten: "Sumba Timur",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.0239, lng: 120.7979,
    nama: "Tanah Peternakan",
    alamat: "Desa Kabaru, Kec. Rindi, Kab. Sumba Timur, NTT",
    kondisi: "Sisa tanah kosong peternakan",
    luas: "19.524 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "HP. 00002/2023 — dikelola BPAD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 00002/2023",
    keterangan: "Sisa tanah kosong peternakan yang belum dimanfaatkan. Dikelola BPAD.",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 37,
    pemanfaat: "Tanah Ruko Friendship (Eks Taman APDN)",
    lokasi: "Jl. Soeharto, depan Hotel Sylvia, Kel. Naikoten I",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.181118, lng: 123.600201,
    nama: "Tanah Bangunan Pertokoan/Rumah Toko/Koperasi",
    alamat: "Jl. Soeharto, depan Hotel Sylvia, Kel. Naikoten I, Kota Kupang, NTT",
    kondisi: "Tanah/bangunan",
    luas: "4.375 m²",
    klasifikasi: "Tanah dan bangunan aset Pemprov NTT",
    statusHak: "HP. 473/1987 — dikelola BPAD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "HP. 473/1987",
    keterangan: "Tanah Ruko Friendship (Eks Taman APDN). Dikelola BPAD.",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 38,
    pemanfaat: "Tanah Belakang Hotel Cendana",
    lokasi: "Jl. Hati Suci, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.168917, lng: 123.602188,
    nama: "Tanah Belakang Hotel Cendana",
    alamat: "Jl. Hati Suci, Kota Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "29.670 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "Dikelola BPAD",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "—",
    keterangan: "Tanah belakang Hotel Cendana. Dikelola BPAD.",
    harga: "Belum dinilai",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: ""
  },
  {
    id: 39,
    pemanfaat: "Tanah Wisata Lasiana",
    lokasi: "Pantai Lasiana, Kota Kupang",
    kabupaten: "Kota Kupang",
    statusPemanfaatan: "Belum Dimanfaatkan",
    statusClass: "belum-dimanfaatkan",
    lat: -10.131553, lng: 123.677132,
    nama: "Tanah Wisata Lasiana",
    alamat: "Lasiana, Kota Kupang, NTT",
    kondisi: "Tanah wisata",
    luas: "5.195 m²",
    klasifikasi: "Tanah aset Pemprov NTT",
    statusHak: "529/2022 — dikelola Dinas Pariwisata dan Ekonomi Kreatif",
    tersedia: "Tersedia — belum dimanfaatkan",
    sertifikat: "529/2022",
    keterangan: "Tanah untuk Wisata Lasiana. Dikelola Dinas Pariwisata dan Ekonomi Kreatif.",
    harga: "Belum dinilai",
    opd: "Dinas Pariwisata dan Ekonomi Kreatif",
    image: ""
  },
  {
    id: 40,
    pemanfaat: "Tanah Tambak Garam — Sudah Diperuntukkan",
    lokasi: "Bipolo, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Dimanfaatkan",
    statusClass: "dimanfaatkan",
    lat: -10.0346043, lng: 123.8033286,
    nama: "Tanah Tambak Garam yang Sudah Diperuntukkan (Hibah Pemerintah Pusat)",
    alamat: "Bipolo, Kab. Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "477.500 m²",
    klasifikasi: "Tanah tambak garam / hibah pemerintah pusat",
    statusHak: "HPL 12/2019 – AAP 626917",
    tersedia: "Tidak tersedia — sedang dimanfaatkan",
    sertifikat: "HPL 12/2019 – AAP 626917",
    keterangan: "Tanah tambak garam hibah Pemerintah Pusat seluas 477.500 m², sudah diperuntukkan. Dikelola Pemprov NTT.",
    harga: "Rp14.707.000.000",
    opd: "",
    image: "asset/Tanah Tambak Garam Bipolo.jpg"
  },
  {
    id: 41,
    pemanfaat: "Tanah Tambak Garam — Sudah Diperuntukkan",
    lokasi: "Oelatimo, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Dimanfaatkan",
    statusClass: "dimanfaatkan",
    lat: -10.023472, lng: 123.852662,
    nama: "Tanah Tambak Garam yang Sudah Diperuntukkan (Hibah Pemerintah Pusat)",
    alamat: "Oelatimo, Kab. Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "189.700 m²",
    klasifikasi: "Tanah tambak garam / hibah pemerintah pusat",
    statusHak: "HPL 13/2019 – AAP 626918",
    tersedia: "Tidak tersedia — sedang dimanfaatkan",
    sertifikat: "HPL 13/2019 – AAP 626918",
    keterangan: "Tanah tambak garam hibah Pemerintah Pusat seluas 189.700 m², sudah diperuntukkan. Dikelola Pemprov NTT.",
    harga: "Rp6.601.560.000",
    opd: "",
    image: ""
  },
  {
    id: 42,
    pemanfaat: "Tanah Tambak Garam — Sudah Diperuntukkan",
    lokasi: "Nunkurus, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Dimanfaatkan",
    statusClass: "dimanfaatkan",
    lat: -10.0620226, lng: 123.8058053,
    nama: "Tanah Tambak Garam yang Sudah Diperuntukkan (Hibah Pemerintah Pusat)",
    alamat: "Nunkurus, Kab. Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "4.289.000 m²",
    klasifikasi: "Tanah tambak garam / hibah pemerintah pusat",
    statusHak: "HPL 14/2019 – AAP 626919",
    tersedia: "Tidak tersedia — sedang dimanfaatkan",
    sertifikat: "HPL 14/2019 – AAP 626919",
    keterangan: "Tanah tambak garam hibah Pemerintah Pusat seluas 4.289.000 m² (~428,9 ha), sudah diperuntukkan. Dikelola Pemprov NTT.",
    harga: "Rp142.394.800.000",
    opd: "",
    image: "asset/Tambak Garam Nunkurus .jpg"
  },
  {
    id: 43,
    pemanfaat: "Tanah Tambak Garam — Sudah Diperuntukkan",
    lokasi: "Merdeka, Babau, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Dimanfaatkan",
    statusClass: "dimanfaatkan",
    lat: -10.08747, lng: 123.76698,
    nama: "Tanah Tambak Garam yang Sudah Diperuntukkan (Hibah Pemerintah Pusat)",
    alamat: "Merdeka, Babau, Kab. Kupang, NTT",
    kondisi: "Tanah kosong",
    luas: "11.500.000 m²",
    klasifikasi: "Tanah tambak garam / hibah pemerintah pusat",
    statusHak: "HPL 15/2019 – AAP 626920",
    tersedia: "Tidak tersedia — sedang dimanfaatkan",
    sertifikat: "HPL 15/2019 – AAP 626920",
    keterangan: "Tanah tambak garam hibah Pemerintah Pusat seluas 11.500.000 m² (~1.150 ha), sudah diperuntukkan. Dikelola Pemprov NTT.",
    harga: "Rp279.856.500.000",
    opd: "",
    image: "asset/Tambak Garam Merdeka Baubau .jpg"
  },
  {
    id: 44,
    pemanfaat: "Tanah Tambak Garam — Sudah Diperuntukkan",
    lokasi: "Merdeka, Kab. Kupang",
    kabupaten: "Kabupaten Kupang",
    statusPemanfaatan: "Dimanfaatkan",
    statusClass: "dimanfaatkan",
    lat: -10.088, lng: 123.769,
    nama: "Tanah Tambak Garam yang Sudah Diperuntukkan (Hibah Pemerintah Pusat)",
    alamat: "Merdeka, Kab. Kupang, NTT",
    kondisi: "Baik",
    luas: "432.200 m²",
    klasifikasi: "Tanah Kosong Yang Sudah Diperuntukkan",
    statusHak: "HPL 16/2019 – AAP 626921",
    tersedia: "Tidak tersedia — sedang dimanfaatkan",
    sertifikat: "HPL 16/2019 – AAP 626921",
    keterangan: "Tanah tambak garam hibah Pemerintah Pusat seluas 432.200 m², sudah diperuntukkan. Dikelola Pemprov NTT. Dokumen: 19/08/2019.",
    harga: "Rp11.643.468.000",
    opd: "Badan Pendapatan dan Aset Daerah",
    image: "asset/Tambak Garam Merdeka .jpeg"
  }
];